*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
FUNCTION $$UNIT$$ ZGCTS_FM_POC

    IMPORTING
       REFERENCE(I_MATNR) TYPE !MATNR
    EXPORTING
       REFERENCE(E_MAKTX) TYPE !MAKTX .